export const course = [
  { 
    name: 'История транспорта',
    description: '',
    tags: ['транспорт', 'история'],
    hours: 72,
    date: '01.01.2023 — 31.12.2023',
    link: '',
    id: 'course_1',
    active: false,
  },
  { 
    name: 'Россия в\u00A0глобальной истории',
    description: '',
    tags: ['Россия', 'история'],
    hours: 108,
    date: '01.01.2023 — 31.12.2023',
    link: '',
    id: 'course_2',
    active: false,
  },
  { 
    name: 'Системы железнодорожной автоматики и телемеханики',
    description: '',
    tags: ['жд', 'автоматика'],
    hours: 108,
    date: '01.01.2023 — 31.12.2023',
    link: '',
    id: 'course_3',
    active: false,
  },
  { 
    name: 'Человеческий капитал транспорта',
    description: '',
    tags: ['транспорт', 'экономика'],
    hours: 72,
    date: '01.01.2023 — 31.12.2023',
    link: '',
    id: 'course_4',
    active: false,
  },
]
